### ISSUE TITLE
Demo removes <?php line

### ISSUE THREAD

**Issue by escopecz** [rectorphp/getrector.org#124]
Live demo: https://getrector.org/demo/97209fdb-db60-4425-9278-ca2c00e7836c#result

PHP snippet:
```php
<?php declare(strict_types=1);

class CommonDemoFile
{
	public function run(array $params)
    {

    }
}

class DemoFile extends CommonDemoFile
{
    public function run(array $params)
    {
        return $params;
    }
}
```

```yml
# rector.yaml
parameters:
    sets:
        - 'dead-code'
```

Unexpected: Rector removes `<?php declare(strict_types=1);`
