### ISSUE TITLE
[Docker] MySQL not supported on ARM64

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/getrector.org#278]
MySQL does not support ARM: https://github.com/docker-library/mysql/issues/318

This issue is there for 4+ years and does not seem to move anywhere.

I propose switch to MariaDB as it should be 1:1 compatible. 

Currently it means that noone is able to run this in docker on M1 Macbook (or any other ARM based cpu).

**Comment by JanMikes** [comment]
The fastest workaround to make it work without changes locally is to put this into `docker-compose.override.yml`:
```yml
version: "3.7"
services:
    mysql:
        image: mariadb:10.5
```
